package com.minima.meg.mainsite;

import java.io.PrintWriter;

public class header {

	public static void writeHeader(String zLevel, PrintWriter zOut) {
		
		zOut.write("<html>\r\n"
				+ "<head>\r\n"
				+ "	<title>MEG</title>\r\n"
				+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "	<link rel=\"stylesheet\" href=\"style.css\">\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "<center>\r\n"
				+ "\r\n"
				+ "<script type=\"text/javascript\">\r\n"
				+ "	function logout(){\r\n"
				+ "		location.href=\"logoff.html\";\r\n"
				+ "	}\r\n"
				+ "</script>\r\n"
				+ "\r\n"
				+ "<table class=maintable cellpadding=0 cellspacing=0>\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "	<td colspan=2>\r\n"
				+ "		<table class=titletable>\r\n"
				+ "			<tr>\r\n"
				+ "				<td><img src=\"MEG_Icon.png\"></td>\r\n"
				+ "				<td width=100% class=titletext nowrap>Minima Enterprise Gateway</td>\r\n"
				+ "				<td class=logouttext onclick='logout();'><img src=\"logout.png\"></td>\r\n"
				+ "				<td class=logouttext onclick='logout();'>Logout</td>\r\n"
				+ "			</tr>\r\n"
				+ "		</table>\r\n"
				+ "	</td>\r\n"
				+ "</tr>\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "	<td style=\"vertical-align:top;\">\r\n"
				+ "		<table class=menutable height=100%>\r\n"
				+ "			\r\n"
				+ "			<tr><td><div>\r\n"
				+ "				<img style=\"vertical-align:middle\" src=\"Minima_logo.png\">\r\n"
				+ "			</div></td>\r\n"
				+ "			<td nowrap><div>\r\n"
				+ "				<span><a class=menu href='minimanode.html'>Minima Node</a></span>\r\n"
				+ "			</div></td></tr>\r\n"
				+ "			<tr><td>&nbsp;</td></tr>\r\n"
				+ "			\r\n"
				+ "			<tr><td><div>\r\n"
				+ "				<img style=\"vertical-align:middle\" src=\"bolt.png\">\r\n"
				+ "			</div></td>\r\n"
				+ "			<td nowrap><div>\r\n"
				+ "				<span><a class=menu href='triggers.html'>Triggers</a></span>\r\n"
				+ "			</div></td></tr>\r\n"
				+ "			\r\n"
				+ "			<tr><td><div>\r\n"
				+ "				<img style=\"vertical-align:middle\" src=\"line_end_circle.png\">\r\n"
				+ "			</div></td>\r\n"
				+ "			<td nowrap><div>\r\n"
				+ "				<span><a class=menu href='apiendpoints.html'>Endpoints</a></span>\r\n"
				+ "			</div></td></tr>\r\n"
				+ "			\r\n"
				+ "			<tr><td><div>\r\n"
				+ "				<img style=\"vertical-align:middle\" src=\"wallet.png\">\r\n"
				+ "			</div></td>\r\n"
				+ "			<td nowrap><div>\r\n"
				+ "				<span><a class=menu href='wallet.html'>Wallet API</a></span>\r\n"
				+ "			</div></td></tr>\r\n"
				+ "			\r\n"
				+ "			<tr><td>&nbsp;</td></tr>");
		
		//ONLY Admin gets the ADMIN tag
		if(zLevel.equals("admin")) {
			zOut.write("<tr><td><div>\r\n"
					+ "				<img style=\"vertical-align:middle\" src=\"logs.png\">\r\n"
					+ "			</div></td>\r\n"
					+ "			<td nowrap><div>\r\n"
					+ "				<span><a class=menu href='logs.html'>Logs</a></span>\r\n"
					+ "			</div></td></tr>\r\n"
					+ "			\r\n"
					+ "			<tr><td><div>\r\n"
					+ "				<img style=\"vertical-align:middle\" src=\"profile.png\">\r\n"
					+ "			</div></td>\r\n"
					+ "			<td nowrap><div>\r\n"
					+ "				<span><a class=menu href='myprofile.html'>Profile</a></span>\r\n"
					+ "			</div></td></tr>\r\n"
					+ "			\r\n"
					+ "			<tr><td><div>\r\n"
					+ "				<img style=\"vertical-align:middle\" src=\"admin.png\">\r\n"
					+ "			</div></td>\r\n"
					+ "			<td nowrap><div>\r\n"
					+ "				<span><a class=menu href='admin.html'>Admin</a></span>\r\n"
					+ "			</div></td></tr>\r\n"
					+ "			\r\n"
					+ "			<tr><td>&nbsp;</td></tr>");
		}else {
			zOut.write(""
					+ "			<tr><td><div>\r\n"
					+ "				<img style=\"vertical-align:middle\" src=\"logs.png\">\r\n"
					+ "			</div></td>\r\n"
					+ "			<td nowrap><div>\r\n"
					+ "				<span><a class=menu href='logs.html'>Logs</a></span>\r\n"
					+ "			</div></td></tr>\r\n"
					+ "			\r\n"
					+ "			<tr><td><div>\r\n"
					+ "				<img style=\"vertical-align:middle\" src=\"profile.png\">\r\n"
					+ "			</div></td>\r\n"
					+ "			<td nowrap><div>\r\n"
					+ "				<span><a class=menu href='myprofile.html'>Profile</a></span>\r\n"
					+ "			</div></td></tr>\r\n"
					+ "			\r\n"
					+ "			<tr><td>&nbsp;</td></tr>");
		}
				
		zOut.write(""
				+ "<tr><td><div>\r\n"
				+ "				<img style=\"vertical-align:middle\" src=\"help.png\">\r\n"
				+ "			</div></td>\r\n"
				+ "			<td nowrap><div>\r\n"
				+ "				<span><a class=menu href='help.html'>Help</a></span>\r\n"
				+ "			</div></td></tr>\r\n"
				+ "			\r\n"
				+ "			<tr><td height=100%>&nbsp;</td></tr>\r\n"
				+ "		</table>\r\n"
				+ "		\r\n"
				+ "	</td>\r\n"
				+ "	\r\n"
				+ "	<td class=mainview>");
	}
}
